### PR TITLE
Switch to antitypical/Result

### LINKED ISSUE #6: Migrate from LlamaKit to antitypical/Result
As noted in the LlamaKit README, it "has been merged with and superceded by Rob Rix's Result µframework.".

### PR DESCRIPTION
**Pull request by mdiep**
Fixes #6.

### CODE REVIEW

**Comment by mdiep** [comment]
Ugh. I'll have to fix up the settings that Xcode added.

**Comment by mdiep** [comment]
Okay, this is ready to go now.

**Comment by modocache** [comment]
Awesome, thanks @mdiep! I should probably disable Travis since this no longer supports Swift 1.1.

**Comment by paulyoung** [comment]
Looks like the README is now out of date.

**Pull request merged**
