### PR TITLE
Guanaco won't build with Xcode 7.2 that uses Swift 2.0

### PR DESCRIPTION
**Pull request by qnoid**
Happy New Year @modocache 🎉

This update was caused by the need to compile [SwiftGit2](https://github.com/SwiftGit2/SwiftGit2) with Xcode 7.2 and Swift 2.0.

Once this pull request passes code review and is merged, will also work on the SwiftGit2 integration and update to Xcode 7.2 and Swift 2.0.

### CODE REVIEW

**Comment by qnoid** [comment]
While writing a test for _HaveFailed.haveFailed_ to assert that the same error thrown is treated the same way as the error returned in the **Result**, came across the following.

_Expectation.to_ that calls _Expectation.expressionMatches_ treats every error as a failure when trying to evaluate the expression at _Expectation.expressionMatches#10_. Unless you have any ideas, will need to take a better look. It's not clear to me at this time if that's by design or not.

**Comment by qnoid** [comment]
Have opted to not report the failed value in the _failureMessage_, which is why the expression is evaluated, so as to be consistent between a failure in a Result and when an error is thrown where no actual value exists.

By the way, the only reason I decided to keep the Result notation in parallel to Swift's error handling is to avoid any major refactoring to this project and any other using it as a dependency at this time.

**Comment by paulyoung** [comment]
bump :facepunch:

**Comment by modocache** [comment]
Oops, sorry! Will check this out tonight.

**Comment by modocache** [comment]
Thanks! Sorry for taking so long to merge! :bouquet: 

To make sure I don't slow you two down in the future, I've given you both write access. :ok:

**Comment by qnoid** [comment]
@modocache wow, no worries, thanks :)

**Pull request merged**
